apiVersion: v1
kind: Service
metadata:
  name: product-service
  namespace: namespace-workflow-1735560918746
  labels:
    kubernetes.azure.com/generator: devhub
spec:
  type: LoadBalancer
  selector:
    app: product-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80